---
name: Copilot Setup Steps

on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: Copilot
    steps:
      - name: Azure login
        uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
